# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modifed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144, verbose_name='T\xedtulo')),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(verbose_name='Importancia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modifed', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Category')),
            ],
        ),
    ]
