# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Category', verbose_name='Categor\xeda'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='description',
            field=models.TextField(verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='sort_order',
            field=models.BooleanField(verbose_name='Importancia'),
        ),
    ]
