# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170622_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='photo',
            field=models.ImageField(blank=True, upload_to='notice_image'),
        ),
    ]
